### PR TITLE
Fix nav button and settings page layout

### PR DESCRIPTION
**Pull request by SPiCaRiA**
Issue #3 and #4 done. For details please check the subordinate pull requests :)

### CODE REVIEW

**Comment by SPiCaRiA** [comment]
I'll just leave my comments on issue #2 here.

The reason why I did not fix that one as well is because of some discussion needed. The lines related to the line heights are:

```css
/* -- MAKE PARAGRAPH and LINE SPACING EVEN IN READING AND EDIT MODES */
.markdown-preview-view br, .markdown-source-view, br {
  content: '';
  display: block;
  margin-top: calc(var(--custom-line-height) / 2);
}

.markdown-source-view.mod-cm6 .cm-line {
  padding: calc(var(--custom-line-height) / 3) 0px calc(var(--custom-line-height) / 3) 0px;
  line-height: var(--custom-line-height) !important;
}
```

1. I'm confused about the first part on `<br>` elements. First, it seems that Obsidian does not generate `<br>` elements in view mode, which means that they are only used as placeholders under the editor mode. Also, I don't think it is a good idea to override the default line-breaking element into a block content, which in my case I lose my cursors under the Vim mode.
Screen Shot 2023-03-28 at 17 42 37

I highlighted the active line (in grey), which is an empty line of `<br>`, but I cannot see my cursor.
Screen Shot 2023-03-28 at 17 43 57

Non-`<br>` lines work fine.

2. For the second part on`.cm-line`s, I cannot see any difference from changing the `line-height`, so I can't tell much about it. But for the padding, which essentially causes #2, I'm not sure if we really want to add such space between lines. I don't think Notion is doing the same space, and it is also rarely seen in other themes.

Just my PO, I would suggest removing these codes, but I'm not sure how you think @Bluemoondragon07 .

**Comment by Bluemoondragon07** [comment]
Thank you so much for making this pull request! It makes maintaining the theme a lot easier, and I appreciate it.

1. The inclusion of `br` in the first part is to add extra space between blocks of text in Reading Mode, even if the block below is not a real paragraph. For example, when `enter` is pressed once instead of twice, it makes it look like a real paragraph with an extra margin at the top. I included this because at the time I thought it made it look more WYSIWYG like Notion, but now that I see that it causes issues for Vim mode, I think it's  not necessary.

2. For the second part...I think the line height was meant to force spacing in lists. I'm not sure why I used `.cm-line` instead of `.cm-list`, but I believe that the code can be safely removed. As for padding, I believe I put it there for more consistency with line spacing in Reading Mode. Even though I do like the consistency, I agree that it is not necessary, especially since it is interfering with spacing in code blocks. Still, I think I may be able to exclude lines inside a code block from this padding. 

### Solution
I will attempt to exclude code blocks from the extra padding and line height. Then I think I will make a "Consistent Paragraphs" style setting so that this code will only be activated if it is toggled on. That way, the consistent spacing can still be an option, but people will be able to turn it on and off if they want.  I'll try to get this in an update this weekend. In the meanwhile, thank you for pointing out all these issues and helping me fix them, I really do appreciate it.

**Comment by Bluemoondragon07** [comment]
Also, thanks for making the settings more accurate to Notion. I didn't look too much into specific padding values, so I think it's really cool that you added in those improvements.

**Comment by SPiCaRiA** [comment]
> Thank you so much for making this pull request! It makes maintaining the theme a lot easier, and I appreciate it.

Sure! I like the theme you made :)



> 2\. As for padding, I believe I put it there for more consistency with line spacing in Reading Mode. Even though I do like the consistency, I agree that it is not necessary, especially since it is interfering with spacing in code blocks. Still, I think I may be able to exclude lines inside a code block from this padding.

If I'm understanding correctly, I guess you are trying to mimic this `16px` space **between paragraphs** (which is to say, at least 2 enters were pressed). 

Screen Shot 2023-03-28 at 20 04 04


But it seems that the padding code ends up adding the space to all lines. For example:

Under view mode:
```markdown
some text
<space of 16px>
some other text
```
The total height of above things is: `line-height + 16px + line-height`

Under editor mode:
```markdown
some text (with top/bottom padding of 8px)
<empty line>
some other text (with top/bottom padding of 8px)
```
And the total height becomes: `8px + line-height + 8px * 2 + line-height + 8px * 2 + line-height`

Now I kinda understand why you want to modify the `<br>` element: to mimic the `16px` space (though the padding is still not necessary).

Given the cursor issue when we modify the `<br>` element, I'm afraid that the consistency is hard to archieve (at least from my knowledge). The core problem is that, the `16px` space under view mode is the "natural" space between `display: block` elements (in our case, the `<p>` elements).

Actually I think we should not make this "natural" space under editor mode, because Obsidian provides a setting option "Editor - Strict line breaks", which treat one enter as line break when set to false. In that case, we don't get the `<br>` element under editor mode anymore, since the second enter is not needed. Therefore, the above approach of mimicing the "natural" space will be screwed up completely, even if we ignore the cursor issue.

I guess the idea is, we are supposed to respect (and show) the enters in source/live preview mode, so users know what they are typing. But when displaying them, the Markdown specification takes over and decide how many line breaks will be rendered. And we don't need to bother aligning these two things, cuz they are meant to be different all the way!

-----

Though the editor/view mode consistency is not very practical, we can turn to be consistent with Notion: add `padding: 3px 2px` to the lines.

Screen Shot 2023-03-28 at 20 06 47

Which at least in my PO, looks good :)

Screen Shot 2023-03-28 at 20 08 56

**Comment by Bluemoondragon07** [comment]
I like your idea of making the padding to be `3px 2px` like Notion. And yeah, I think perhaps I went too far with modifying the appearance of edit mode to be something it is not meant to be. I'm also really new to css so I mostly created this theme through trial and error rather than thinking things through 😅. I think I will get rid of the even line spacing by default, but still have it as an available setting.

**Pull request merged**
